#!/bin/bash

# How to running ubuntu Container

# get ubuntu container from Docker hub
docker run ubuntu

#History of container that were exited
docker ps -a

#alternative docker command "docker ps -a"
docker container ls -a

#Run ubuntu container and get into it.
docker run -it ubuntu

# size of ubuntu image download it by the container

dokcer images.

# Creating Linux Container using a smallest image possible (busybox)
#busybox is not a fully fit linux distribution

docker run busybox

# Get Alpine Image container (alpine is based on busybox with additional utilities).
docker pull alpine
