#!/bin/bash

ocker pull monog   # pull mongodb image from docker hub

docker run mongo   # run mongodb image

docker ps  # check running containers

docker ps -a  # check all containers

docker stop <container_id>  # stop container

docker exec -it <container_id> bash  # run bash in container.   #  -it  is for interactive mode

 docker exec -it <container_id> mongosh  # run mongodb shell in container to manipulate Database

 docker stop <container_id>  # stop container

 docker start <container_id>  # start container

 docker run -d -v $PWD/db:/data/db mongo    # run mongodb container in background and mapping host directory to container directory